id: A3909E4C8
title: Long-Life Prayer Presented to the Incarnation of Shukseb Jetsünma
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:38:21.966092
  last_modified_at: 2022-03-01 00:38:21.966096
